### ISSUE TITLE
Examples require images directory

### ISSUE THREAD

**Issue by psiphi75** [plotters-rs/guide#2]
All the examples require an "images" directory.  On the first page of the documentation if you run

```sh
cargo run --bin 2_1_chart_context
```

The example will panic and with the following message:

```txt
thread 'main' panicked at 'Unable to save the bitmap: DrawingError(IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', src/libcore/result.rs:1165:5
```

If you add an `image/` folder, it works.

**Comment by 38** [comment]
Thanks, already added!

**Comment by jakubGodula** [comment]
Hi, I've tried adding both image/ and images/ folders in root dir of my project as well as in ~/.cargo/.../plotter.<version>/ but I keep getting the following error.
> thread 'main' panicked at 'Unable to save the bitmap: DrawingError(IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', /home/jakub/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.2.12/src/drawing/backend_impl/bitmap.rs:1001:13

I've tried setting up an absolute path,
> BitMapBackend::new("/home/jakub/soft/mooj/plotter/first/images/sierpinski.png", (1024, 768)).into_drawing_area();
but it still gives the same error, so how do I define a valid path in project's directory?


P.S. Sorry for a noob's question.
